{"root":{"data":{"text":"java异常处理","expandState":"expand"},"children":[{"data":{"text":"异常发生的原因","expandState":"collapse"},"children":[{"data":{"text":"用户输入了非法数据。"},"children":[]},{"data":{"text":"要打开的文件不存在。"},"children":[]},{"data":{"text":"网络通信时连接中断，或者JVM内存溢出"},"children":[]}]},{"data":{"text":"Throwable","expandState":"collapse"},"children":[{"data":{"text":"Error","note":"Error：表示由 JVM 所侦测到的无法预期的错误，由于这是属于 JVM 层次的严重错误，导致 JVM 无法继续执行，因此，这是不可捕捉到的，无法采取任何恢复的操作，顶多只能显示错误信息。"},"children":[]},{"data":{"text":"Exception","expandState":"collapse"},"children":[{"data":{"text":"所有的异常类是从 java.lang.Exception 类继承的子类"},"children":[]},{"data":{"text":"Exception 类是 Throwable 类的子类"},"children":[]},{"data":{"text":"比如：IOException，RuntimeException"},"children":[]}]}]},{"data":{"text":"捕获异常","expandState":"collapse"},"children":[{"data":{"text":"try/catch","note":"```\ntry{\n\t// 程序代码\n}catch(异常类型1 异常的变量名1){\n\t// 程序代码\n}catch(异常类型2 异常的变量名2){\n\t// 程序代码\n}catch(异常类型2 异常的变量名2){\n\t// 程序代码\n}\n\n```"},"children":[]},{"data":{"text":"throws/throw","expandState":"collapse"},"children":[{"data":{"text":"如果一个方法没有捕获一个检查性异常，那么该方法必须使用 throws 关键字来声明"},"children":[]},{"data":{"text":"throws 关键字放在方法签名的尾部"},"children":[]},{"data":{"text":"也可以使用 throw 关键字抛出一个异常"},"children":[]},{"data":{"text":"一个方法可以声明抛出多个异常，多个异常之间用逗号隔开"},"children":[]}]},{"data":{"text":"finally","expandState":"collapse"},"children":[{"data":{"text":"finally 关键字用来创建在 try 代码块后面执行的代码块。"},"children":[]},{"data":{"text":"无论是否发生异常，finally 代码块中的代码总会被执行。"},"children":[]},{"data":{"text":"在 finally 代码块中，可以运行清理类型等收尾善后性质的语句。"},"children":[]},{"data":{"text":"finally 代码块出现在 catch 代码块最后","note":"```\ntry{\n\t// 程序代码\n}catch(异常类型1 异常的变量名1){\n\t// 程序代码\n}catch(异常类型2 异常的变量名2){\n\t// 程序代码\n}finally{\n\t// 程序代码\n}\n\n```"},"children":[]}]}]}]},"template":"default","theme":"fresh-blue","version":"1.4.43"}